### ISSUE TITLE
Hello Tsoding gf2 and thx for your programming streams.

### ISSUE THREAD

**Issue by patrikgafvert** [tsoding/todo.asm#8]
I see your struggle with gf2, have you seen that gf2 have a way of saving the config and so on. If you read the README.md from the git repo you have lots of config options.
Like layout.

https://github.com/nakst/gf#user-interface

Of cource you can close this issue then you read it.

Best regards
//Patrik

**Comment by rexim** [comment]
out side of the scope of the project
